"""first

Revision ID: 2f21b6f50cf4
Revises:
Create Date: 2018-10-14 09:15:09.701745

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '2f21b6f50cf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('created_at', models.PendulumDateTime(timezone=True), nullable=False),
        sa.Column('updated_at', models.PendulumDateTime(timezone=True), nullable=False),
        sa.Column('external_id', sa.String(length=36), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('external_id')
    )
    op.create_table(
        'chore_definition',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('created_at', models.PendulumDateTime(timezone=True), nullable=False),
        sa.Column('updated_at', models.PendulumDateTime(timezone=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('owner_id', sa.String(length=32), nullable=False),
        sa.Column('details', sa.Text(), nullable=False),
        sa.Column('frequency_amount', sa.Integer(), nullable=False),
        sa.Column('frequency_type', sa.Enum('DAYS', 'WEEKS', 'MONTHS', 'YEARS', name='frequencytypes'), nullable=False),
        sa.CheckConstraint('frequency_amount >= 0', name='check_frequency_amount_positive'),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'chore_instance',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('created_at', models.PendulumDateTime(timezone=True), nullable=False),
        sa.Column('updated_at', models.PendulumDateTime(timezone=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('details', sa.Text(), nullable=False),
        sa.Column('owner_id', sa.String(length=32), nullable=False),
        sa.Column('chore_definition_id', sa.String(length=32), nullable=False),
        sa.Column('due_date', models.PendulumDateTime(timezone=True), nullable=False),
        sa.Column('completed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['chore_definition_id'], ['chore_definition.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chore_instance')
    op.drop_table('chore_definition')
    op.drop_table('user')
    # ### end Alembic commands ###
