"""deleted field

Revision ID: 647105091bf6
Revises: 2f21b6f50cf4
Create Date: 2018-10-20 16:30:52.441292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647105091bf6'
down_revision = '2f21b6f50cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_definition', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chore_instance', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), server_default=sa.literal('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    op.drop_column('chore_instance', 'deleted')
    op.drop_column('chore_definition', 'deleted')
    # ### end Alembic commands ###
